main: net.dylanhansch.lavahub.Lavahub
name: Lavahub
version: 1.0
description: Master bukkit plugin for the Lavahub Network.
author: Dylan Hansch
website: http://dylanhansch.net/
commands:
    action:
        description: Send action message
        usage: /<command> <message>
        aliases: [me]
    clearinventory:
        description: Clear player inventory
        usage: /<command> <player>
        aliases: [ci, clear]
    gamemode:
        description: Change player gamemode
        usage: /<command> <mode> <player>
        aliases: [gm]
    hack:
        description: Hack the server
        usage: /<command>
    ping:
        description: Debugging tool for awesome developers
        usage: /<command>
    say:
        description: Send message as console
        usage: /<command> <message>
    time:
        description: Set world time
        usage: /<command> <day|noon|night>
permissions:
    lavahub.*:
        default: op
    lavahub.action:
        default: op
    lavahub.clearinventory:
        default: op
    lavahub.clearinventory.others:
        default: op
    lavahub.gamemode:
        default: op
    lavahub.gamemode.others:
        default: op
    lavahub.hack:
        default: true
    lavahub.ping:
        default: true
    lavahub.say:
        default: op
    lavahub.time:
        default: op