main: net.dylanhansch.lavahub.Lavahub
name: Lavahub
version: 1.0
description: Master bukkit plugin for the Lavahub Network.
author: Dylan Hansch
website: http://dylanhansch.net/
commands:
    rawmsg:
        description: Send raw message
        usage: /<command> <message>
    say:
        description: Send message as console
        usage: /<command> <message>
    setspawn:
        description: Set server spawn
        usage: /<command>
    spawn:
        description: Teleport to server spawn
        usage: /<command> <player>
permissions:
    lavahub.rawmsg:
        default: op
    lavahub.say:
        default: op
    lavahub.setspawn:
        default: op
    lavahub.spawn:
        default: op