main: net.dylanhansch.lavahub.Lavahub
name: Lavahub
version: 1.0
description: Master bukkit plugin for the Lavahub Network.
author: Dylan Hansch
website: http://dylanhansch.net/
commands:
    clearinventory:
        description: Clears player inventory
        usage: /<command> <player>
        aliases: [ci, clear]
    hack:
        description: Hack the server
        usage: /<command>
    ping:
        description: Debugging tool for awesome developers
        usage: /<command>
permissions:
    lavahub.*:
        default: op
    lavahub.clearinventory:
        default: op
    lavahub.clearinventory.others:
        default: op
    lavahub.hack:
        default: true
    lavahub.ping:
        default: true