main: ${main.class}
name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Dylan Hansch
website: ${project.url}
commands:
    action:
        description: Send action message
        usage: /<command> <message>
        aliases: [me]
    clearchat:
        description: Clears chat
        usage: /<command> <me/all>
    deafen:
        description: Deafen a player
        usage: /<command> <player>
        aliases: [deaf]
    lavahub:
        description: Reload Lavahub configuration from disk
        usage: /<command>
    mute:
        description: Mute a player
        usage: /<command> <player>
    rawmsg:
        description: Send raw message
        usage: /<command> <message>
    undeafen:
        description: Undeafen a player
        usage: /<command> <player>
        aliases: [undeaf]
    unmute:
        description: Unmute a player
        usage: /<command> <player>
permissions:
    lavahub.*:
        description: Lavahub Admin
        default: op
        children:
            lavahub.action: true
            lavahub.clearchat: true
            lavahub.clearchat.all: true
            lavahub.deafen: true
            lavahub.reload: true
            lavahub.mute: true
            lavahub.rawmsg: true
            lavahub.undeafen: true
            lavahub.unmute: true
